(async function(){
const base='./';
const version='20260915a';
const radioFiles=['data/radios_01.js','data/radios_02.js','data/radios_03.js','data/radios_04_1.js','data/radios_04_2.js','data/radios_04_3.js','data/radios_04_4.js','data/radios_04_5.js','data/radios_05_1.js','data/radios_05_2.js'];
async function ft(p){const r=await fetch(base+p+'?v='+version,{cache:'no-store'});if(!r.ok)throw Error(`No se pudo descargar ${p} (HTTP ${r.status})`);return r.text()}
function arr(c,p){const q=c.indexOf('.concat('),s=c.indexOf('[',q);if(q<0||s<0)throw Error(`Formato inesperado ${p}`);let d=0,z=false,e=false;for(let i=s;i<c.length;i++){const x=c[i];if(z){if(e){e=false;continue}if(x==='\\'){e=true;continue}if(x==='"')z=false;continue}if(x==='"'){z=true;continue}if(x==='[')d++;else if(x===']'){d--;if(d===0)return JSON.parse(c.slice(s,i+1))}}throw Error(`Array incompleto ${p}`)}
function compact(c){const k='window.STUDENT_COMPACT=',a=c.indexOf(k);if(a<0)throw Error('Formato de estudiantes inesperado');const s=a+k.length,e=c.lastIndexOf(';');return JSON.parse(c.slice(s,e))}
function ring(pt,r){const x=pt[0],y=pt[1];let inside=false;for(let i=0,j=r.length-1;i<r.length;j=i++){const xi=r[i][0],yi=r[i][1],xj=r[j][0],yj=r[j][1];if(((yi>y)!=(yj>y))&&(x<(xj-xi)*(y-yi)/(yj-yi)+xi))inside=!inside}return inside}
function poly(pt,g){if(g.type==='Polygon')return ring(pt,g.coordinates[0]);if(g.type==='MultiPolygon')return g.coordinates.some(p=>ring(pt,p[0]));return false}
const IA=['ChatGPT','Meta','Gemini','Copilot','Notebook Gemini','Claude','DeepSeek','Qwen'];
try{window.RADIOS_RAW=[];for(const p of radioFiles)window.RADIOS_RAW.push(...arr(await ft(p),p));if(window.RADIOS_RAW.length!==524)throw Error(`Se cargaron ${window.RADIOS_RAW.length} radios; se esperaban 524`);const pts=compact(await ft('data/students.js'));const features=pts.map(([x,y,m])=>({type:'Feature',geometry:{type:'Point',coordinates:[x,y]},properties:{ias:IA.filter((_,i)=>m&(1<<i)),mask:m,pct_nbi:null,radio:null,dentro:false}}));window.STUDENT_DATA={type:'FeatureCollection',features};const geos=window.RADIOS_RAW.map(r=>({r,g:{type:r[5],coordinates:r[6]},counts:{},n:0}));let assigned=0;features.forEach((f,idx)=>{const [x,y]=f.geometry.coordinates,m=pts[idx][2];const hit=geos.find(o=>poly([x,y],o.g));if(!hit)return;assigned++;hit.n++;f.properties.pct_nbi=Number(hit.r[1]);f.properties.radio=hit.r[0];f.properties.dentro=true;IA.forEach((name,i)=>{if(m&(1<<i))hit.counts[name]=(hit.counts[name]||0)+1})});for(const o of geos){o.r[2]=o.n;o.r[4]=o.counts;o.r[3]=Object.entries(o.counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'Sin IA'}const active=geos.filter(o=>o.n>0).length;const gc=document.getElementById('geoCount'),rc=document.getElementById('radioCount');if(gc)gc.textContent=String(pts.length);if(rc)rc.innerHTML=`${active} <em>/ 524</em>`;window.GEO_STATS={total:pts.length,assigned,active};console.log('Radios:',window.RADIOS_RAW.length,'Georreferenciadas publicables:',pts.length,'Dentro de San Martín:',assigned,'Radios activos:',active);(0,eval)(await ft('app.js'))}catch(err){console.error(err);const m=document.getElementById('map');if(m)m.innerHTML='<div style="padding:24px;color:#fff;background:#7f1d1d;font:14px system-ui"><b>Error cargando las capas censales.</b><br>'+String(err.message||err)+'</div>'}
})();